export const CLUSTER_IPC_INSTANCE = Symbol('CLUSTER_IPC_INSTANCE');
export const CLUSTER_IPC_OPTIONS = Symbol('CLUSTER_IPC_OPTIONS');
export const CLUSTER_IPC_LISTENER_METADATA = Symbol('CLUSTER_IPC_LISTENER_METADATA');
